import type { Metadata } from "next";
import Head from "next/head";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/utils/ThemeProvider";

const fontName = Public_Sans({
  weight: ["400", "500", "600", "700"],
  variable: "--font-name",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={fontName.className}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
